### ISSUE TITLE
Regarding the Haskell representation of th PGSQL `text` and `bytea` types

### ISSUE THREAD

**Issue by Kleidukos** [ed-o-saurus/PLHaskell#1]
Hi! I wanted to know if there had been technical reasons that led you to represent the `text` type with `[Char]` on the Haskell side. Similarly with `bytea` and ByteString.

Cheers! :)

**Comment by ed-o-saurus** [comment]
No particular reason. It just seamed the simplest approach.

**Comment by Kleidukos** [comment]
Thanks for the answer! Would you accept a PR in this direction? Lazy linked lists do not offer the best asymptotics nor the best API for textual data representation. :)

**Comment by ed-o-saurus** [comment]
I've changed to the code to use ByteString/Text in commit 232ed51ee6f63aa0701dc1af0532702de3122c9b.
This was a good suggestion.
