### ISSUE TITLE
Compile with optimizations

### ISSUE THREAD

**Issue by arybczak** [ed-o-saurus/PLHaskell#6]
I might be missing something, but it looks like `ghc` invocations in the Makefile do not apply any optimization to both `Haskell` and `C` files.

**Comment by ed-o-saurus** [comment]
That may be the case. If you see a possible improvement, let me know, or submit a pull-request.

**Comment by ed-o-saurus** [comment]
Changed in [v2.1](https://github.com/ed-o-saurus/PLHaskell/releases/tag/2.1).

**Comment by ed-o-saurus** [comment]
Changed in v2.1
